version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/hhumphrey84/unblocked
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm ci
      - run: npm run cypress:verify
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./home/circleci/.cache/Cypress
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: e2e
          command: npm run test:cypress
